server {
    listen 8000;
    server_name 859707243.xyz;


    # 2. 原有的 Vue 静态文件与路由配置
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # 解决 Vue Router history 模式刷新 404 的核心配置
        try_files $uri $uri/ /index.html;
    }

    # 3. 开启 gzip 压缩
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
}
